### ISSUE TITLE
Unable to load addon script

### ISSUE THREAD

**Issue by ChildishGiant** [arypbatista/godot-bordered-polygon-2d#45]
Unable to load addon script from path: 'res://addons/bordered-polygon-2d/register.gd' There seems to be an error in the code, please check the syntax.    

`error(7, 87): Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.`

**Comment by jtaart** [comment]
Sorry, it's pretty out of date.  If I remember right we wrote it for Godot 2.1. I may update it sooner or later. 

[Platform2D](https://godotengine.org/asset-library/asset/29) is more up to date, but you might still have to fix some stuff for it to work in 3.2.

**Comment by arypbatista** [comment]
Merged Pull Request #44 which migrated the addon to Godot 3.x.

I will update the addon on the asset library asap
